application: social-simulator
version: 1
runtime: php
api_version: 1

handlers:
- url: /(.*\.(php|html))$
  script: \1

- url: /
  script: index.php

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /.*
  script: index.php